/* eslint-disable */
import { Post } from "./Post";
import post_0 from "../../articles/2017-9-4 有感.md";
import post_1 from "../../articles/AsyncDisplayKit 2.1 Gif错误.md";
import post_2 from "../../articles/Autolayout 和 size-class 简明教程.md";
import post_3 from "../../articles/charles 4.1 破解.md";
import post_4 from "../../articles/extern与static用法.md";
import post_5 from "../../articles/Hadoop Hive 环境搭建.md";
import post_6 from "../../articles/Hashimoto IO bound proof of work.md";
import post_7 from "../../articles/hexo SEO 优化.md";
import post_8 from "../../articles/hexo 增加Mathjax支持.md";
import post_9 from "../../articles/hexo 增加本地搜索模块.md";
import post_10 from "../../articles/hexo 增加目录.md";
import post_11 from "../../articles/hexo 标题自动转换为拼音.md";
import post_12 from "../../articles/hexo 自定义辅助类.md";
import post_13 from "../../articles/Html 字符串转换成 AttributedString ios版本下的错误 - 副本.md";
import post_14 from "../../articles/IOS shadowColor 动画 卡顿.md";
import post_15 from "../../articles/IOS Tips 小集合.md";
import post_16 from "../../articles/IOS 绘制 录音波形图.md";
import post_17 from "../../articles/ios 防御战.md";
import post_18 from "../../articles/IOS10前 UITextFiled 的 placeholder 的问题.md";
import post_19 from "../../articles/IOS逆向学习.md";
import post_20 from "../../articles/Mongoose 学习.md";
import post_21 from "../../articles/Nodejs Async 学习.md";
import post_22 from "../../articles/objc学习之路-inline - 副本.md";
import post_23 from "../../articles/objc学习之路-inline.md";
import post_24 from "../../articles/Paxos Made Live - An Engineering Perspective.md";
import post_25 from "../../articles/paxos-simple.md";
import post_26 from "../../articles/Practical Byzantine Fault Tolerance.md";
import post_27 from "../../articles/Pthreads 学习1 - 一览.md";
import post_28 from "../../articles/Pthreads 学习2 - 文档.md";
import post_29 from "../../articles/Pthreads 学习3 - 信号量.md";
import post_30 from "../../articles/Pthreads 学习4 - 锁.md";
import post_31 from "../../articles/reactivex 学习.md";
import post_32 from "../../articles/realm-cocoa 学习.md";
import post_33 from "../../articles/RxSwift Moya 实际项目实践.md";
import post_34 from "../../articles/RxSwift 学习.md";
import post_35 from "../../articles/Spring boot Mybatis 学习.md";
import post_36 from "../../articles/Spring boot 服务器.md";
import post_37 from "../../articles/swagger 学习.md";
import post_38 from "../../articles/travis-ci 来维护 Cocoapods.md";
import post_39 from "../../articles/UIButton disable 触发事件.md";
import post_40 from "../../articles/UITextFiled NSTextAlignment.right 空格问题.md";
import post_41 from "../../articles/UITextFiled 最大长度.md";
import post_42 from "../../articles/web3js 学习 智能合约学习.md";
import post_43 from "../../articles/WebKit WkwebView dealloc Crash错误.md";
import post_44 from "../../articles/WebView 与 Html Input Bug.md";
import post_45 from "../../articles/WKWebView IOS8 下 loadHtmlString错误.md";
import post_46 from "../../articles/WKWebView 制作详情页的一些经验.md";
import post_47 from "../../articles/Xcode 8 点击Stop 没有反应,卡死问题.md";
import post_48 from "../../articles/Xcode 关键字不高亮显示.md";
import post_49 from "../../articles/使用 NodeJS APNS 给你的应用发消息.md";
import post_50 from "../../articles/使用dataTable来展示修改历史专栏.md";
import post_51 from "../../articles/八爪鱼 获取用户鼠标悬浮层级.md";
import post_52 from "../../articles/关于小额贷款api分析.md";
import post_53 from "../../articles/关于弹射面试题的思考.md";
import post_54 from "../../articles/分布网络-共识算法.md";
import post_55 from "../../articles/创建自己的Cocoapods源.md";
import post_56 from "../../articles/制作一个自己的 Cydia 源.md";
import post_57 from "../../articles/区块链 p2p认识.md";
import post_58 from "../../articles/大话数据结构-串.md";
import post_59 from "../../articles/大话数据结构-数据结构绪论.md";
import post_60 from "../../articles/大话数据结构-栈与队列.md";
import post_61 from "../../articles/大话数据结构-树.md";
import post_62 from "../../articles/大话数据结构-算法.md";
import post_63 from "../../articles/大话数据结构-线性表.md";
import post_64 from "../../articles/奇怪的 unrecognized selector sent to instance 问题.md";
import post_65 from "../../articles/手势密码解锁界面.md";
import post_66 from "../../articles/比特币隔离见证和闪电网络理解.md";
import post_67 from "../../articles/测试.md";
import post_68 from "../../articles/终端优化 历程.md";
import post_69 from "../../articles/给博客文章增加修改历史专栏.md";
import post_70 from "../../articles/马甲包 ios.md";

const posts = ([post_0,post_1,post_2,post_3,post_4,post_5,post_6,post_7,post_8,post_9,post_10,post_11,post_12,post_13,post_14,post_15,post_16,post_17,post_18,post_19,post_20,post_21,post_22,post_23,post_24,post_25,post_26,post_27,post_28,post_29,post_30,post_31,post_32,post_33,post_34,post_35,post_36,post_37,post_38,post_39,post_40,post_41,post_42,post_43,post_44,post_45,post_46,post_47,post_48,post_49,post_50,post_51,post_52,post_53,post_54,post_55,post_56,post_57,post_58,post_59,post_60,post_61,post_62,post_63,post_64,post_65,post_66,post_67,post_68,post_69,post_70] as unknown) as [Post];

export { posts };